### ISSUE TITLE
Issue connecting to backblaze client

### ISSUE THREAD

**Issue by DocN** [microcompiler/backblaze#11]
Message = "Error converting value \"readBuckets\" to type 'Bytewizer.Backblaze.Models.Capability'. Path 'allowed.capabilities[6]', line 14, position 19."

Anyone have any idea? The API key I setup has access to 'readBuckets'

*edit
Appears the api has new return values that aren't supported by the current version. Also the UploadAsync function appears to be super slow when uploading files of any size. Anyone experiencing this?

**Comment by cxnky** [comment]
yep, just got this

**Comment by neildanson** [comment]
Same here. Any clues on how to fix?

**Comment by neildanson** [comment]
Adding 
`ReadBucketEncryption,
WriteBucketEncryption,`

to Capabilities.cs and building from source fixed for me. Will try to get time to submit a patch later

**Comment by neildanson** [comment]
See https://github.com/microcompiler/backblaze/pull/12
