### ISSUE TITLE
UriFormatExceptionSystem thrown when calling UploadAsync

### ISSUE THREAD

**Issue by skauge** [microcompiler/backblaze#5]
First off: Thank you for making a nice client for the Backblaze B2 API!

When calling UploadAsync in BackblazeAgent the following exception is thrown:
System.UriFormatException: 'Invalid URI: The format of the URI could not be determined.'

I believe the exception happens when UploadFileByBucketIdRequest.cs tried to convert the filename into a URI. Notice I'm trying to give only the filename - not the entire file path.

Example code:

```
foreach (var filepath in Directory.GetFiles(@"c:\my\directory"))
{
  using (var stream = File.OpenRead(filepath))
    await storage.UploadAsync(new UploadFileByBucketIdRequest(bucket.BucketId, new System.IO.FileInfo(filepath).Name), stream);
}
```

If I choose the absolute filepah the uploads succeed. Unfortunately, in Backblaze, my local full path is stored - not just the filename as wished.

**Comment by microcompiler** [comment]
Thank you for the detailed example.  This is a very valid use case that I had not considered that the B2 API fully supports.  At first glance it looks like I will need to move away from URI and build a custom parser.  Let me dig into it.

**Comment by phosphene47** [comment]
This is still happening with the latest Nuget package which doesn't contain the fix commit.

**Comment by phosphene47** [comment]
Upon inspection, this seems to happen with other requests as well.

- `CopyFileRequest`
- `DownloadFileByNameRequest`

**Comment by microcompiler** [comment]
Package version 0.8.4 resolves this issue for all endpoints.  Please don't hesitate to let me know if you any other issues.
