### ISSUE TITLE
Ability to initialize the client without dependency injection

### ISSUE THREAD

**Issue by phosphene47** [microcompiler/backblaze#6]
As the title says, it would be nice to have a constructor of `BackblazeAgent` that can be used manually instead of utilizing the dependency container.

Or at least provide an example to construct the client and its dependencies manually, in the README.

**Comment by seertenedos** [comment]
Further to this the method
`public static ApiClient Initialize(string keyId, string applicationKey)`
is one option i tried using for this but it complains the HTTPClient is null on the first call out.

**Comment by microcompiler** [comment]
Version 0.9.1 allows the client to initialize without dependency injection.   A new package Backblaze.Client was published.   See the [README](https://github.com/microcompiler/backblaze/blob/master/README.md) for usage examples.

`BackblazeClient.Initialize("[key_id]", [application_key]");`
